name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: clear setting xml
      env: 
        GITHUB_TOKEN: ${{ secrets.var_token_for_publish_to_github }}
      run: |
        mkdir ~/.m2
        echo "<settings xmlns=\"http://maven.apache.org/SETTINGS/1.0.0\"  xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"  xsi:schemaLocation=\"http://maven.apache.org/SETTINGS/1.0.0                      http://maven.apache.org/xsd/settings-1.0.0.xsd\">  <activeProfiles>    <activeProfile>github</activeProfile>  </activeProfiles>  <profiles>    <profile>      <id>github</id>      <repositories>        <repository>          <id>central</id>          <url>https://repo1.maven.org/maven2</url>          <releases><enabled>true</enabled></releases>          <snapshots><enabled>true</enabled></snapshots>        </repository>        <repository>          <id>github</id>          <name>GitHub tiznin Apache Maven Packages</name>          <url>https://maven.pkg.github.com/tiznin</url>        </repository>      </repositories>    </profile>  </profiles>  <servers>    <server>      <id>github</id>      <username>tiznin</username>      <password>${GITHUB_TOKEN}</password>    </server>  </servers></settings>" > ~/.m2/settings.xml
    - name: Build with Maven and deploy
      run: mvn package
    - name: deploy
      run: mvn -X -Dregistry=https://maven.pkg.github.com/tiznin deploy
